In [ ]:
# Learned NumPy fundamentals – array creation, indexing, and slicing.
# Performed mathematical, axis-wise, and statistical operations on datasets.
# Applied reshaping and broadcasting techniques for efficient computation.
# Implemented save/load operations for NumPy arrays.
# Compared NumPy’s performance with standard Python lists.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [3]:
# 0-D Arrays

arr0 = np.array(42)
print(arr0)

42

In [4]:
# 1-D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]

In [5]:
# 2-D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]

In [6]:
# 3-D Arrays
arr3 = np.array ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print (arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

In [8]:
# Check number of dimentions
# Use ndim to check number of Dimentions in Array

print ( f"{arr.ndim} + {arr0.ndim} + {arr1.ndim} + {arr2.ndim} + {arr3.ndim}" )

1 + 0 + 1 + 2 + 3

In [10]:
#Higher Dimentional Arrays 
arr5 = np.array([1,2,3,4,5,6,7,8,9], ndmin = 15)
print(arr5)

print ("number if dimentions:", arr5.ndim)

[[[[[[[[[[[[[[[1 2 3 4 5 6 7 8 9]]]]]]]]]]]]]]]
number if dimentions: 15

In [13]:
# Array Indexing 
arr
print(arr[0])

1

In [12]:
print(arr)

[1 2 3 4 5]

In [14]:
arr2Dtest = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2Dtest)
# [RowIndex,ColumnIndex]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [16]:
print('2nd element on 1st row: ', arr2Dtest[0, 1])

2nd element on 1st row:  2

In [17]:
arr3Dtest =  np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#[ Leaf , Row, Column ] 

print(arr3Dtest)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

In [18]:
print(arr3Dtest[0, 1, 2])

6

In [19]:
#Negative Indexing 
arrNeg = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arrNeg [1, -1])

Last element from 2nd dim:  10

In [22]:
# Slicing Arrays 

# We pass slice instead of index like this: [start:end]
# We can also define the step, like this: [start:end:step].

ArrPreSlice = np.array ( [1,2,3,4,5,6,7,9,10] )
ArrPostSlice =  ArrPreSlice [1:5]
print ( ArrPostSlice )

[2 3 4 5]

In [23]:
print ( ArrPreSlice[5:])

[ 6  7  9 10]

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]

In [27]:
# Use Step to Determine the step in Slicing 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]

In [29]:
# Performed mathematical, axis-wise, and statistical operations on datasets.

In [12]:
## Project 2 
import pandas as pd

df = pd.read_csv("student_data.csv")
df.head

<bound method NDFrame.head of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>

In [5]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [6]:
arr

NameError: name 'arr' is not defined

In [7]:
arr0

NameError: name 'arr0' is not defined

In [8]:
print(arr0)

NameError: name 'arr0' is not defined

In [9]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [10]:
df.rename(columns = {'sex':'gender'}, inplace = True)

In [11]:
df

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [13]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [14]:
df.rename(columns = {'sex':'gender'}, inplace = True)

In [17]:
df.dtypes

school        object
gender        object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [29]:
# We will now compute the Mean, Median, and Mode for Age, G1, G2, G3. 
mean_age = df['age'].mean()
median_age = df['age'].median()
mode_age = df['age'].mode()
variance_age = df ['age'].var()
max_age = df ['age'].max()
min_age = df ['age'].min()
count_age = df['age'].count()

print("mean Age:", mean_age)
print("median Age:", median_age)
print("modal Age:", mode_age)
print("variance in Age:",variance_age)
print("max age", max_age)
print("min age", min_age)
print("count age", count_age)

mean Age: 16.696202531645568
median Age: 17.0
modal Age: 0    16
Name: age, dtype: int64
variance in Age: 1.6282850350189455
max age 22
min age 15
count age 395

In [32]:
columns = ["age","G1","G2","G3"] 

for column in columns:
    print (f" Mean  {column} -   : {df[column].mean()}")
    print (f" Mode  {column} -   : {df[column].mode()}")
    print (f" Median  {column} - : {df[column].median()}")
    print (f" Variance {column} -: {df[column].var()}")
    print (f" Maximum {column} - : {df[column].max()}")
    print (f" Minimum {column} - : {df[column].min()}")
    print (f" Count {column} -   : {df[column].count()}")
    print("============================================")

 Mean  age -   : 16.696202531645568
 Mode  age -   : 0    16
Name: age, dtype: int64
 Median  age - : 17.0
 Variance age -: 1.6282850350189455
 Maximum age - : 22
 Minimum age - : 15
 Count age -   : 395
============================================
 Mean  G1 -   : 10.90886075949367
 Mode  G1 -   : 0    10
Name: G1, dtype: int64
 Median  G1 - : 11.0
 Variance G1 -: 11.017053267364899
 Maximum G1 - : 19
 Minimum G1 - : 3
 Count G1 -   : 395
============================================
 Mean  G2 -   : 10.713924050632912
 Mode  G2 -   : 0    9
Name: G2, dtype: int64
 Median  G2 - : 11.0
 Variance G2 -: 14.148917303861756
 Maximum G2 - : 19
 Minimum G2 - : 0
 Count G2 -   : 395
============================================
 Mean  G3 -   : 10.415189873417722
 Mode  G3 -   : 0    10
Name: G3, dtype: int64
 Median  G3 - : 11.0
 Variance G3 -: 20.989616397866737
 Maximum G3 - : 20
 Minimum G3 - : 0
 Count G3 -   : 395
============================================

In [ ]:
# Filter rows, select columns and slice subsets.

In [39]:
#Filter Age to find those older than 18 
df[df['age']>18]

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,2,7,8,9
153,GP,M,19,U,GT3,T,3,2,services,at_home,...,4,5,4,1,1,4,0,5,0,0
210,GP,F,19,U,GT3,T,3,3,other,other,...,4,3,3,1,2,3,10,8,8,8
247,GP,M,22,U,GT3,T,3,1,services,services,...,5,4,5,5,5,1,16,6,8,8
257,GP,M,19,U,LE3,A,4,3,services,at_home,...,4,3,1,1,1,1,12,11,11,11
270,GP,F,19,U,GT3,T,3,3,other,services,...,4,3,5,3,3,5,15,9,9,9
296,GP,F,19,U,GT3,T,4,4,health,other,...,2,3,4,2,3,2,0,10,9,0
304,GP,M,19,U,GT3,T,3,3,other,other,...,4,4,4,1,1,3,20,15,14,13
306,GP,M,20,U,GT3,A,3,2,services,other,...,5,5,3,1,1,5,0,17,18,18
307,GP,M,19,U,GT3,T,4,4,teacher,services,...,4,3,4,1,1,4,38,8,9,8
308,GP,M,19,R,GT3,T,3,3,other,services,...,4,5,3,1,2,5,0,15,12,12
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,4,4,3,1,3,3,18,12,10,10
310,GP,F,19,U,LE3,T,1,2,services,services,...,4,2,4,2,2,3,0,9,9,0
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,3,4,1,1,1,2,20,14,12,13
312,GP,M,19,U,GT3,T,1,2,other,services,...,4,5,2,2,2,4,3,13,11,11
313,GP,F,19,U,LE3,T,3,2,services,other,...,4,2,2,1,2,1,22,13,10,11
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,4,1,2,1,1,3,14,15,13,13
315,GP,F,19,R,GT3,T,2,3,other,other,...,4,1,2,1,1,3,40,13,11,11
336,GP,F,19,R,GT3,A,3,1,services,at_home,...,5,4,3,1,2,5,12,14,13,13
340,GP,F,19,U,GT3,T,2,1,services,services,...,4,3,4,1,3,3,4,11,12,11
350,MS,M,19,R,GT3,T,1,1,other,services,...,5,4,4,3,3,2,8,8,7,8
353,MS,M,19,R,GT3,T,1,1,other,other,...,4,4,4,3,3,5,4,8,8,8
370,MS,F,19,U,LE3,T,3,2,services,services,...,3,2,2,1,1,3,4,7,7,9
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
383,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,6,5,0
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [38]:
df[df['age']<18]
#People aged less that 18.

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16

In [46]:
# first 5 Students who have scored less than average in each Grade.
print(f"{df['G1'].mean()}")
df[df['G1']<df['G1'].mean()].head()

10.90886075949367

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6

In [48]:
# first 5 Students who have scored more  than average in each Grade.
print(f"{df['G1'].mean()}")
df[df['G1']>df['G1'].mean()].head()

10.90886075949367

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

In [56]:
columns = ["age","G1","G2","G3"] 
print("Learners above average in each grade")
for column in columns:
    print(f"{df[column].mean()}")
    df[df[column]>df[column].mean()].head()
    print("==================================================================================")

df[df[column]>df[column].mean()]

Learners above average in each grade
16.696202531645568
==================================================================================
10.90886075949367
==================================================================================
10.713924050632912
==================================================================================
10.415189873417722
==================================================================================

,school,gender,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,19,18,19
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
378,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,0,15,15,15
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16